name: carzone
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0



  # Image picker
  image_picker: ^1.1.1

  # File system helpers
  path_provider: ^2.1.2
  path: ^1.9.0

  # State management (optional but recommended)
  provider: ^6.1.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
